### ISSUE TITLE
please add license

### ISSUE THREAD

**Issue by skippy** [lloyd/yajl#155]
hey @lloyd 
the source files generally have a license, but can you add a license file for the project?  

thank you!

**Comment by envygeeks** [comment]
This software does have a DFSG/Linux package style License, see: https://github.com/lloyd/yajl/blob/master/COPYING

**Comment by adolphenom** [comment]
You can see that this piece of software is actually Free Software as Wikipedia means: https://es.wikipedia.org/wiki/Licencia_ISC

**Comment by skippy** [comment]
@envygeeks thanks for pointing that one out. closing!
